### ISSUE TITLE
Missing DesignSurface in VS2022 Designer Extensibility support for net6.0-windows Windows Forms controls

### ISSUE THREAD

**Issue by ilCosmico** [microsoft/winforms-designer-extensibility#24]
With reference to [this issue](https://developercommunity.visualstudio.com/t/VS2022-Designer-Extensibility-support-fo/1487318), I have read the paragraph _“Migrating existing Control Designers with almost no effort”_ of [this article](https://devblogs.microsoft.com/dotnet/custom-controls-for-winforms-out-of-process-designer/), but I am having trouble building my custom ControlDesigner in .NET6 due to the absence of the [`DesignSurface` class](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.design.designsurface?view=windowsdesktop-7.0). Let me explain in detail. (**I already tried with NET7, but the issue still persists**).

My `MyControlDesigner` class uses a derived Form class called `VisualControlDesigner` to display an additional popup for customizing the user control.  
(Picture shows it in action in a .NET Framework project)  
![image](https://github.com/microsoft/winforms-designer-extensibility/assets/8678145/04121697-3780-4aba-a111-8e4ed475f091)

It internally uses a class called `DesignSurfaceExt`, which is derived from `System.ComponentModel.Design.DesignSurface`.  
However, I cannot locate it in .NET6, as shown in the following image.  
![image](https://github.com/microsoft/winforms-designer-extensibility/assets/8678145/c94332cf-6a2a-4166-892e-8f61852a87bb)

Moreover, `MyControlDesigner` class uses some adorners, which is not an issue, as demonstrated in the following picture.  
![image](https://github.com/microsoft/winforms-designer-extensibility/assets/8678145/3313072e-021e-44fb-843d-7b17a1b11f1b)

To help you understand it better, here is a short video demonstrating both Adorners and Visual Control Designer in action in a NetFramework project: [https://www.screencast.com/t/ZIdrCvojT9d](https://www.screencast.com/t/ZIdrCvojT9d).

**Comment by KlausLoeffelmann** [comment]
I saw the video, and was impressed by the sophistication of this Designer. At the same time, these are the scenarios which in all honesty need - let's put it this way: the most love to port to the Out-Of-Proc Designer.

While I don't have the complete picture yet why you might need `DesignSurface` for that implementation, the fact is that the `DesignSurface` you will ultimately end up with, FWIW, will be the Framework version, simply, because there is not .NET equivalent that would even come to any deployment.

Everything which is UI-related need to be done in the context of .NET Framework and the VS process. So, there will be no rendering on the Serverside, except for the actual control's content and the adorners. So, the Designer Frame, the Behavior service along with the Adorner Overlay and then the actual Designers, which become part of that whole tree when needed. But that bunch of Windows (all being created in the .NET Server Process) get parented - tadah! - to the Client Process based on `DesignSurface` (and others in betweem). In the .NET process, there is a) no DesignSurface and b) the (modal WinForms TypeEditor-based) Dialogs cannot be kicked of from the .NET Server but only from the .NET Framework Client Process.

For that particular scenario that means some adaptation work: Type Discovery, of course, needs to be done server-side, because Framework does not have "access" to the .NET type information. If .NET is needed to actually render something in particular, then the only way to that is render the result into a Bitmap's HDC, and then request that Bitmap from the respective (Client-side-shown) TypeEditor from the Server. Same is true for everything, which needs to be presented for example in a TreeView Client-side, which only the Server knows about: That information needs to be collected on the server, and then send back to the client, which then can present it in the TypeEditor's dialog.

Hope this helps as a starting point - keep the questions coming!

**Comment by ilCosmico** [comment]
@KlausLoeffelmann `DesignSurface` seems to be included in .NET as described [here](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.design.designsurface?view=windowsdesktop-7.0). Why I cannot use it on the Serverside?

Please check out [this additional video](https://www.screencast.com/t/Kixt6sF1vAr8), which focuses on the .Net Framework version of our component. The video demonstrates the many interactions between the Visual Control Designer and the custom control. You'll notice that every inner element of the custom control is customizable, and the Visual Control Designer picture is updated in real-time. Our approach is similar to the one used by `DesignSurfaceExt`, which is showcased in this [sample](https://www.codeproject.com/Articles/1174241/DesignSurfaceExtended-the-third-chapter-how-to-imp). The `DesignSurfaceExt` has a method `CreateControl` to interact in real-time with a control. Currently, we're using it to make the Visual Control Designer work.

[Here](https://github.com/microsoft/winforms-designer-extensibility/files/12596029/MyNet6ControlWinForms.zip) is a sample project showing a very very simplified control. Is it possible to have a version of this project that shows how to use the `DesignSurface` in the Client to achieve a similar result as in .Net Framework?

![image](https://github.com/microsoft/winforms-designer-extensibility/assets/8678145/24e73401-4fec-43a6-94cc-097bee39ec2b)

P.S. Product is Eyeshot. You can download a copy [here](https://www.devdept.com/Products/Download) if need to make some tests on .Net Framework designer.

**Comment by ilCosmico** [comment]
> Please [read this blog post](https://devblogs.microsoft.com/dotnet/custom-controls-for-winforms-out-of-process-designer/) to understand the interaction between Visual Studio as a Client and the DesignToolsServer of the WinForms Designer in the WinForms Designer context.

You should know that I already read it more than once. You also included it in [the issue](https://developercommunity.visualstudio.com/t/VS2022-Designer-Extensibility-support-fo/1487318) where you requested me to open this one to provide me with better assistance. However, I am still having difficulty achieving my goal. 

If it is not too much trouble, would you mind adding some code to the [NET6 sample project I shared](https://github.com/microsoft/winforms-designer-extensibility/files/12596396/MyNet6ControlWinForms.zip) to help me better understand? 
Thank you for your help in advance.

**Comment by KlausLoeffelmann** [comment]
Unfortunately, I don't have the time at this point to ramp-up in that sample project.

But maybe we can compromise by drilling down in little steps to the area, where we can do a better explanation job, to get you unblocked.

So, with that suggested: 
Where do the missing information from your perspective start?

**Comment by KlausLoeffelmann** [comment]
To your question about using a .NET 6 control in a .NET Framework process: No, that's not possible. If you have a .NET 6 control, which renders, the only way to mitigate that issue is, to render the output server-side for example to a Bitmap's DC, and then transport the bitmap back, or implement something like a rendering redirector, which would "ask" the server how to render the respective parts inside of a Framework process.

**Comment by ilCosmico** [comment]
> Where do the missing information from your perspective start?

I started working with [your sample code](https://github.com/KlausLoeffelmann/NetControlDesigners) several months ago, I even submitted a Pull request for a bug, but it seems to have been overlooked. Nonetheless, that is not my main concern. I am currently unable to locate a sample code that addresses my specific needs. Have you made any improvements to the sample code that I may have missed?

Thank you.

**Comment by ilCosmico** [comment]
I was finally able to find a solution without using DesignSurface.
